server:
  port : 8090
spring:
  profiles:
    active: local
  cache:
    type: caffeine
    cache-names: tokenCache
    caffeine:
      spec: "maximumSize=100,expireAfterWrite=1800s"
  #  jpa:
  #    hibernate:
  #      ddl-auto: create
  datasource:
    url: jdbc:postgresql://ep-twilight-sound-50986431.ap-southeast-1.aws.neon.tech/neondb
    username: anuragsrmcse
    password: 9o0FtwHCMJmN
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html